acara/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.list),
    path('update/<id_acara>', views.update),
    path('add/', views.add),
    path('store/', views.store),
    path('edit/<id_acara>/', views.edit),
    path('delete/<id_acara>', views.delete)
]

peminjaman/urls.py
from django.urls import path
from django.conf.urls import url, include
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#url for app

urlpatterns = [
    path('', index, name = "index"),
    path('form-peminjaman', create, name = "form_peminjaman")
]

rent_a_bike/urls.py
import voucher.urls as voucher
import peminjaman.urls as peminjaman
from django.urls import path, include
from django.urls import path, include
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('stasiun/', include(('stasiun.urls', 'stasiun'), namespace='stasiun')),
    path('sepeda/', include(('sepeda.urls', 'sepeda'), namespace='sepeda')),
    path('penugasan/', include(('penugasan.urls', 'penugasan'), namespace='penugasan')),
    path('acara/', include(('acara.urls', 'acara'), namespace='acara')),
    path('voucher/', include(voucher)),
    path('peminjaman/', include(peminjaman)),
    path('transaksi/', include('transaksi.urls')),
    path('auth/', include('gauth.urls')),
    path('', views.index)
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

peminjaman/models.py
from django.db import models
from django.db import connection

# Create your models here.
SCHEMA = "bike_sharing"

ANGGOTA = SCHEMA + "." + "anggota"
PEMINJAMAN = SCHEMA + "." + "peminjaman"
SEPEDA = SCHEMA + "." + "sepeda"
STASIUN = SCHEMA + "." + "stasiun"

cursor =  connection.cursor()

class Peminjaman:

    def get_all_peminjaman():
        query = 'select * from %s ;' % (peminjaman)
        cursor.execute(query)
        return cursor

    def get_peminjaman_by_id(member, sepeda):
        query = 'select * from %s where no_kartu_anggota = \'%d\' and nomor_sepeda = \'%d\';' % (PEMINJAMAN, member, sepeda)
        cursor.execute(query)
        return cursor

    def get_peminjaman_and_join_anggota_sepeda():
        query = '''select CAST (pm.no_kartu_anggota AS INTEGER) as no_kartu_anggota, pm.nomor_sepeda as nomor_sepeda, sp.merk as merk_sepeda,
                    pm.id_stasiun as id_stasiun, st.nama as nama_stasiun,
                    pm.datetime_kembali as datetime_kembali, pm.biaya as biaya, pm.denda as denda
                    from %s as pm,
                    %s as a,
                    %s as sp,
                    %s as st
                    where pm.no_kartu_anggota = a.no_kartu
                    and pm.nomor_sepeda = sp.nomor
                    and pm.id_stasiun = st.id_stasiun
                    order by no_kartu_anggota asc
                    ;
                ''' % (PEMINJAMAN, ANGGOTA, SEPEDA, STASIUN)
        cursor.execute(query)
        return cursor

    def get_all_stasiun():
    	query = 'select * from %s ;' % (STASIUN)
    	cursor.execute(query)
    	return cursor

# Create your models here.

peminjaman/views.py
# Create your views here.

from django.shortcuts import render
from .models import Peminjaman

def get_as_dict(cursor):
    columns = [column[0] for column in cursor.description]
    results = []
    for row in cursor.fetchall():
        results.append(dict(zip(columns, row)))
    return results

def index(request):
    context = {
        "peminjaman" : get_as_dict(Peminjaman.get_peminjaman_and_join_anggota_sepeda())
    }
    # print(len(context["sepedas"]))
    # print(context["sepedas"])
    return render(request, 'daftar_peminjaman.html', context)
def create(request):
	context = {
        "stasiuns" : get_as_dict(Peminjaman.get_all_stasiun())
    } 
	return render(request, 'form_peminjaman.html', context)

peminjaman/templates/daftar_peminjaman.html
{% extends 'base.html' %}

{% load static %}

{% block style %}

<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">

{% endblock %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
        <h1>
          List Peminjaman
        </h1>
        <a class="btn btn-primary" href="{% url 'form_peminjaman'%}">
          Create Peminjaman
        </a>
    </div>

    <div class="row">
      <div class="md-form mb-4">
        <input class="form-control" type="text" placeholder="Search" aria-label="Search">
      </div>
      <div class="dropdown ml-3">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Filter By
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="#">Nomor</a>
          <a class="dropdown-item" href="#">Sepeda</a>
          <a class="dropdown-item" href="#">Stasiun</a>
        </div>
      </div>
    </div>

  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col" href="#">No Kartu Anggota</a>
          <th scope="col" href="#">Sepeda</th>
          <th scope="col" href="#">Stasiun</th>
          <th scope="col" href="#">Waktu Kembali</th>
          <th scope="col" href="#">Biaya</th>
          <th scope="col" href="#">Denda</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
          <tbody>
          {% for p in peminjaman %}
          <tr>
            <th scope="row">{{ p.no_kartu_anggota }}</th>
            <td>{{ p.nomor_sepeda }} - {{ p.merk }}</td>
            <td>{{ p.id_stasiun }} - {{ p.nama_stasiun }}</td>
            <td>{{ p.datetime_kembali }}</td>
            <td>{{ p.biaya }}</td>
            <td>{{ p.denda }}</td>
            <td>
              <span>
                <a class="btn btn-primary" href="edit/{{ voucher.id }}">Kembalikan</a>
              </span>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
        </div>

        <nav aria-label="Page navigation example">
         <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
{% endblock %}

peminjaman/templates/form_peminjaman.html
{% extends 'base.html' %}

{% load static %}

{% block style %}

  <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">

{% endblock %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
        <h1>
          Add Peminjaman
        </h1>
    </div>
    <div class="div">
      <div class="row">
        <div class="col-md-12">
            <div class="form-group">
              <label for="usr">Nama Stasiun:</label>
              <select class="form-control" id="exampleFormControlSelect1">
                {% for stasiun in stasiuns %}
                  <option>{{ stasiun.nama }}</option>
                {% endfor %}
              </select>
            </div>
            <span>
              <a class="btn btn-primary" href="{% url 'sepeda:index'%}">Save</a>
            </span>  
            <span>
              <button class="btn btn-danger">Delete</button>
            </span>  
        </div>
      </div>
    </div>
      </div>
    </div>
  </div>
{% endblock %}